apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-microservice1
  labels:
    app: eks-microservice1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-microservice1
  template:
    metadata:
      labels:
        app: eks-microservice1
    spec:
      containers:
      - name: eks-microservice1
        image: 364654941093.dkr.ecr.us-east-1.amazonaws.com/eks-test/web/prod:232ddc25
        ports:
        - containerPort: 8000
          name: http-server
